### PR TITLE
Add basic testing infrastructure

### PR DESCRIPTION
**Pull request by psavery**
This includes a test that starts hexrdgui, loads an instrument config
file, and then loads some data.

This is a work in progress.

Fixes: #889

### CODE REVIEW

**Comment by joelvbernier** [comment]
We should probably get this in place soon, but can defer until October...

**Comment by psavery** [comment]
@joelvbernier Indeed. If this was merged, it would have actually caught the breakpoint in #1023.

**Comment by psavery** [comment]
I think this can actually be ready for review and merging. Currently, all it does is load an instrument config file and load data, and confirm that these were successful. This can already catch some issues, though, such as the `breakpoint()` I accidentally left in #1023 (the tests failed with that change, and now they are passing again due to #1027).

**Review by cjh1 — APPROVED** [review]
LGTM

**Pull request merged**
