### PR TITLE
Mask by shape

### PR DESCRIPTION
**Pull request by bnmajor**
Add the ability to mask images with ellipse or rectangle shapes.

Addresses #432

### CODE REVIEW

**Comment by bnmajor** [comment]
mask-by-shape

**Comment by bnmajor** [comment]
This branch currently provides basic functionality for masking images by shape:

- Can select between rectangle or ellipse
- Selections are applied to each view (raw, cartesian, and polar)
- Masked selections are remembered when toggling between tabbed/untabbed views
- All selections made before pressing `Okay` are treated as one mask

Features that are still needed:

- [ ] Masks available in mask manager
- [ ] Option to export mask(s) - Will add to mask manager dialog
- [ ] Speed up drawing of shape (need to redraw subplot instead of entire canvas)

**Comment by bnmajor** [comment]
@joelvbernier This currently works for masking while in the raw view only. Do these masks also need to be able to be drawn in polar view?

**Comment by joelvbernier** [comment]
@bnmajor yes, would be nice to do either.  We can transform coordinates back from the polar view to raw pixel indices.

**Comment by bnmajor** [comment]
The mask manager now has the option to export masks. Right-clicking on a mask will provide a context menu to export an individual mask, or the export button at the bottom can be used to export all visible masks into a single `npz` file.
export_masks


The option to mask in polar view has also been added, and masks applied in either raw view are applied to polar and vice versa.
applytopolar


Masking cannot currently be done in and is not applied to the cartesian view. This would be simple to add if needed.

**Pull request merged**
