### PR TITLE
Move hand picked fibers into standalone widget

### PR DESCRIPTION
**Pull request by psavery**
This widget will be re-used in the future for Laue spots on normal views.

Currently, it does not support that, but moving the logic into a
standalone widget is a necessary first step.

### CODE REVIEW

**Review by joelvbernier — APPROVED** [review]

**Comment by joelvbernier** [comment]
@psavery -- one strange behavior: the selector on the eta-omega widget doesn't affect any changes unless I switch focus to the main window, then re-focus on the eta-omega widget.  Thoughts?

**Review by joelvbernier — COMMENTED** [review]
@psavery -- one strange behavior: the selector on the eta-omega widget doesn't affect any changes unless I switch focus to the main window, then re-focus on the eta-omega widget.  Thoughts?

**Comment by psavery** [comment]
> @psavery -- one strange behavior: the selector on the eta-omega widget doesn't affect any changes unless I switch focus to the main window, then re-focus on the eta-omega widget. Thoughts?

Is this on Mac? It sounds like that SDK issue we were running into on Mac a while back.

**Comment by joelvbernier** [comment]
On Linux!

**Pull request merged**
