### PR TITLE
Materials panel overhaul

### LINKED ISSUE #598: Remove sglite usage
This will be done after the demo, most likely.

We are currently using `hexrd.spacegroup` just a little bit in the material editor widget, to get things like the hall symbol, required lattice parameters, etc. We should move away from using that module to other alternatives in the repo, because sglite is going to be removed soon.

### PR DESCRIPTION
**Pull request by psavery**
This PR is going to re-design some parts of the materials panel, as per user requests.

The first step was to move some widgets out of the tab widget. You can see an example attached.
Screenshot from 2021-03-04 16-32-16

Some things left to do:
- [x] Move "Min d-spacing" out of "Space Group Info" into untabbed region as well
- [x] Use scientific spin boxes for all floats
- [x] Have user select lattice type, then space group, then space group setting
~~- [x] Make slider view for lattice parameters~~
- [x] Fix #598
- [x] Add c/a ratio editor for space groups 75 -  194

### CODE REVIEW

**Comment by psavery** [comment]
So, apparently, we aren't using sglite after all. We are only using dictionaries in the `hexrd.spacegroup` module...

**Comment by psavery** [comment]
@joelvbernier This currently just moves some of the pieces out of the "General" tab for the materials, and clarifies the "Computed" min d-spacing (used for hexrd computations including Laue overlays) vs. the "Displayed" min d-spacing (used to display powder overlays).

Screenshot from 2021-08-30 11-45-58

Although I didn't check off all the items, I think it's ready for merging, and we can check off more items later.

**Comment by psavery** [comment]
@joelvbernier The merge conflicts were fixed.

**Comment by joelvbernier** [comment]
Regarding @saransh13 comment above, can we add an optional widget to specify c/a for hexagonal/trigonal/rhombohedral lattice types?  A helper that will modify the c parameter based on input a and the ratio.

**Comment by saransh13** [comment]
If space group is in the range 75-194 (inclusive), then we should let the users specify c/a and c (or a) should be set based on the value of a (or c)

**Pull request merged**
