### PR TITLE
Ensure overlay visibility checkbox is updated on state load

### LINKED ISSUE #1552: Overlays visible on state load
After loading a state file, the `show overlay` check box is off but the overlays are visible on the canvas. Screenshot below
Screen Shot 2023-08-02 at 10 16 53 AM

### PR DESCRIPTION
**Pull request by bnmajor**
Fixes #1552

### CODE REVIEW

**Comment by psavery** [comment]
This looks like it works, but emitting this signal might have other side effects like regenerating overlays (the signal is primarily intended to communicate that overlays need to be regenerated).

Could we instead try adding `self.materials_panel.update_gui_from_config()` to [here](https://github.com/HEXRD/hexrdgui/blob/ebbd67518a3fb09e243f9f7fc68e88c9291a4b03/hexrd/ui/main_window.py#L335)?

**Comment by bnmajor** [comment]
> Could we instead try adding `self.materials_panel.update_gui_from_config()` to [here](https://github.com/HEXRD/hexrdgui/blob/ebbd67518a3fb09e243f9f7fc68e88c9291a4b03/hexrd/ui/main_window.py#L335)?

Sure thing.

**Comment by psavery** [comment]
> > Could we instead try adding `self.materials_panel.update_gui_from_config()` to [here](https://github.com/HEXRD/hexrdgui/blob/ebbd67518a3fb09e243f9f7fc68e88c9291a4b03/hexrd/ui/main_window.py#L335)?
> 
> Sure thing.

That needs to be changed to `self.materials_panel.update_gui_from_config()`. Can you also verify that fixes the issue?

**Comment by bnmajor** [comment]
> That needs to be changed to `self.materials_panel.update_gui_from_config()`. Can you also verify that fixes the issue?

I'm sorry, I read your original comment too fast. This is fixed now and that does work.

**Comment by psavery** [comment]
> > That needs to be changed to `self.materials_panel.update_gui_from_config()`. Can you also verify that fixes the issue?
> 
> I'm sorry, I read your original comment too fast. This is fixed now and that does work.

Great! I think this makes more sense too, since updating the GUI is what we are really doing.

**Review by psavery — APPROVED** [review]
LGTM

**Pull request merged**
