### PR TITLE
Add ability to change color map in fit grains

### PR DESCRIPTION
**Pull request by bnmajor**
Addresses #674

### CODE REVIEW

**Comment by psavery** [comment]
This looks great, and works well! But I think there's one thing that might make it a little nicer. Notice the combo options is a big list that covers a lot of the screen:

big_list

For the color map editor in the main window, it is a small list, that only displays 5 items at a time:

small_list

It might be nice to make it a small list as well for the one in the grain fitting results dialog. I think we did this by editing the styleSheet and maxVisibleItems in Qt designer for the combo box. You can see the options we set for the main window one here:

Screenshot from 2020-12-22 11-32-12

**Comment by bnmajor** [comment]
@psavery It looks like the `maxVisibleItems` is currently set to 10, but is still showing that massive list (a quick test lowering that value seemed to make no difference). I could be missing something else though, I'll check it out.

**Comment by psavery** [comment]
@bnmajor Yeah, I don't know why we have to edit the style sheet as well. But we do!

**Review by psavery — APPROVED** [review]
LGTM

**Pull request merged**
