### PR TITLE
Add conda install instructions

### PR DESCRIPTION
**Pull request by cjh1**
@bnmajor I know you were interested in trying out conda. Could you test that these install instruction work for you?

### CODE REVIEW

**Comment by bnmajor** [comment]
@cjh1 I was unable to install with these instructions and got the following error:

```
Traceback (most recent call last):
  File "/home/brianna/anaconda3/envs/test_hexrd/bin/hexrdgui", line 7, in <module>
    from hexrd.ui.main import main
  File "/home/brianna/anaconda3/envs/test_hexrd/lib/python3.8/site-packages/hexrd/ui/main.py", line 8, in <module>
    from hexrd.ui.main_window import MainWindow
  File "/home/brianna/anaconda3/envs/test_hexrd/lib/python3.8/site-packages/hexrd/ui/main_window.py", line 12, in <module>
    from hexrd.ui.calibration_config_widget import CalibrationConfigWidget
  File "/home/brianna/anaconda3/envs/test_hexrd/lib/python3.8/site-packages/hexrd/ui/calibration_config_widget.py", line 10, in <module>
    from hexrd.ui.hexrd_config import HexrdConfig
  File "/home/brianna/anaconda3/envs/test_hexrd/lib/python3.8/site-packages/hexrd/ui/hexrd_config.py", line 11, in <module>
    from hexrd.config.loader import NumPyIncludeLoader
ModuleNotFoundError: No module named 'hexrd.config.loader'
```

This is in a fresh conda environment with no config file, python 3.8.3 in the env.

**Comment by cjh1** [comment]
@bnmajor Thanks, I think i know what the issue is, I will push a PR soon.

**Comment by cjh1** [comment]
@bnmajor Looks like no change is required, I remove an old package from anaconda, can you try in a fresh environment?

**Comment by bnmajor** [comment]
@cjh1 Re-tried with a fresh environment and it works great, sorry about that!

**Comment by cjh1** [comment]
@bnmajor Not your fault that was a genuine issue, thanks for testing it.

**Pull request merged**
