### PR TITLE
Update default material file

### PR DESCRIPTION
**Pull request by saransh13**
Updated the default material file as suggested in issue #580 
The key for the default material was also updated from `ceo2` to `CeO2` to reflect changes in the `material.h5` file.

### CODE REVIEW

**Comment by psavery** [comment]
So, one thing to note here is that currently, in the GUI, when the program starts, it generates new `PlaneData` objects for all of the materials, as this is part of the [Material object initialization](https://github.com/HEXRD/hexrd/blob/f1a7cbc198817e9e996a6dad31aeca09c6fab524/hexrd/material.py#L174), and it currently creates a material object for all the materials at start-up.

This `PlaneData` object generation is expensive, and the more materials we have in the file, the slower the GUI start-up time will be. It's good to have many materials in the HDF5 file. But we might need to prioritize some kind of lazy initialization of the material objects. This is being tracked in #497

**Comment by saransh13** [comment]
Got it. I can think of strategies to do a quicker generation of `planeData`. Most of the time spent in the `Material` class generation is actually in the initialization of the `unitcell` class, which in turn is used to initialize `planeData`

**Comment by psavery** [comment]
@saransh13 Okay. We might want to delay the unit cell class generation as well, then. I'll think of something.

**Comment by cjh1** [comment]
Is there a copy of `materials.h5` in hexrd and hexrdgui?

**Comment by psavery** [comment]
Looks like it is only in hexrdgui right now.

**Comment by cjh1** [comment]
@joelvbernier @saransh13 Is this eventually going to live in hexrd?

**Comment by saransh13** [comment]
@joelvbernier will prob make the final call, but having it in `heXRD` makes more sense to me.

**Comment by cjh1** [comment]
@saransh13 Does this now include LiF, MgO, diamond, sapphire, quartz, ceria, as requested in #580 ?

**Comment by saransh13** [comment]
@cjh1 yes, includes all of them, but @joelvbernier requested a few more additions (LaB6, Silicon, and Forsterite). I'll be pushing those changes today and then we'll be ready to merge.

**Comment by saransh13** [comment]
I think we're ready to merge this now. The startup time was not wildly different.

**Comment by psavery** [comment]
> I think we're ready to merge this now. The startup time was not wildly different.

Great!

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
