### PR TITLE
Add Cartesian feasibility checks and better error messages

### PR DESCRIPTION
**Pull request by psavery**
This adds a few feasibility checks for the Cartesian plot, and it also adds better error messages for both polar and Cartesian modes. The following were added:

1. A memory check for the Cartesian view. If more memory will be used than the available memory, an exception is produced.
2. An angle check for the Cartesian view. If any two detectors have an angle between them greater than 120 degrees, an exception is produced.
3. Better error messages for Cartesian and polar views. Now, if an exception is raised when one is being performed, the message of the exception gets displayed in a QMessageBox for the user to see.

An example is provided below

example

Fixes: #33

### CODE REVIEW

**Comment by joelvbernier** [comment]
This looks great, although I need to rethink the condition for feasibility -- the projection plane normal and beam vector should come into play as well.  Will get back to this tomorrow.

**Comment by psavery** [comment]
@joelvbernier Okay. Yeah, it's currently checking to see if the angle between any two detectors is greater than 120 degrees. But we can change it to whatever is best.

**Comment by cjh1** [comment]
@joelvbernier Any update on what the feasibility check should be?

**Comment by joelvbernier** [comment]
I think perhaps a better approach would be to default to a different view mode.  We could do stereographic instead, which can be computed from the polar view.  Upon further thought, this would make for a better UX than just saying "nope"/  Give me a few hours to test some code.

**Comment by joelvbernier** [comment]
We could just merge this and change later, or update this PR.  Your call.

**Comment by cjh1** [comment]
Yes, lets rebase and merge.

**Comment by psavery** [comment]
I'm on it

**Comment by psavery** [comment]
@cjh1 Ready for review

**Review by cjh1 — APPROVED** [review]
LGTM

**Comment by joelvbernier** [comment]
@psavery and @cjh1 -- I think I have a solution for what to do here.  I will make a stereographic projection to replace the planar projection in the failure case this PR picks up.  Working the function now.

**Pull request merged**
