### PR TITLE
Auto-compute polar resolutions from config

### PR DESCRIPTION
**Pull request by psavery**
When an instrument config file is loaded, or the instrument config
is reset, the polar resolutions are automatically computed and set
based upon the config.

This is currently being done by scaling the max. However, we should
also consider median and min. We most likely need to do some
kind of scaling, so that we can come up with reasonable values for
most instrument configs.

Fixes: #252

To do:
- [x] Figure out how to speed this up. It makes loading new configs and resetting the config much slower.
- [x] Try out a few instrument configs, and ensure [the max](https://github.com/HEXRD/hexrdgui/compare/master...psavery:auto-compute-polar-parameters?expand=1#diff-30bfcc80b3692dfa8947f36bbec62f14R149) is a good option to scale. We can also try the median and the min.
- [x] Try out a few instrument configs, and ensure that [these scaling numbers](https://github.com/HEXRD/hexrdgui/compare/master...psavery:auto-compute-polar-parameters?expand=1#diff-30bfcc80b3692dfa8947f36bbec62f14R155-R156) are satisfactory.

We'd prefer to err on the side of too high of numbers, rather than too low, because too low can potentially make the rendering take a very long time.

### CODE REVIEW

**Comment by cjh1** [comment]
I will that a look a speeding this up.

**Comment by joelvbernier** [comment]
The call to the `pixel_angles` property is the beast.  Could potentially memoize that so that it only updates on change of instrument parameters?  I am all for making this faster, as it affects other things as well.

*OR* we just calculate the ranges _once_ on loading an instrument config.  This should be good enough, as when changing parameters live in the GUI we aren't typically moving things that much, and certainly don't need to update the ranges and pixel size to that precision.  I think that would be the best option, IMHO.  The idea is to get parameters that are roughly appropriate for a given instrument config (_e.g._, the TARDIS goes from ~15-105 degrees, while HEDM instruments cover ~0-20).  The goal is to avoid having an empty polar plot when loading a new config.

**Comment by joelvbernier** [comment]
Thoughts on my second note above?  Only calculate the polar (_and_ cartesian) view parameters on config load?  That would make it much less onerous...

**Comment by psavery** [comment]
@joelvbernier Yep! I think that's how they are set up currently actually. It won't calculate them when you first start up the program (but just load the previously used values). It will only calculate if you either:
1. Load a new instrument config
2. Reset the instrument config

**Comment by psavery** [comment]
@joelvbernier Okay, we can add that code here as well. This branch is currently [only computing the pixel sizes for polar](https://github.com/HEXRD/hexrdgui/pull/388/files#diff-30bfcc80b3692dfa8947f36bbec62f14R135-R156).

But we can add that code to this function to compute the tth min and max too.

**Comment by joelvbernier** [comment]
edited my comment above...

**Comment by joelvbernier** [comment]
Bump on this thread -- I'd say auto-calculating the extents are of primary concern; pixel sizes less so (see previous) until we can speed it up. Thoughts?

**Comment by psavery** [comment]
I think this is working reasonably, and it is ready for review.

I encountered a bug with the polar image extents, but it is unrelated to this PR, and I'll report it in another issue.

**Comment by joelvbernier** [comment]
Thanks guys.

**Pull request merged**
