### PR TITLE
Draw material overlays in raw view

### PR DESCRIPTION
**Pull request by psavery**
This utilizes `PlanarDetector.make_powder_rings()` to draw the material
overlays on the raw view.

It looks good for the most part, except that some detectors produce
`ring_xys` values from `PlanarDetector.make_powder_rings()` that wrap
around to the other side, so that a line is drawn across the detector
connecting the ends. I am not sure if this is something that should
be fixed in hexrdgui, or in hexrd. See "ge2" below for an example.

Additionally, the values do not appear to go all the way to the image
borders for some reason.

Screenshot from 2020-04-16 14-50-50

Screenshot from 2020-04-16 14-52-19

Screenshot from 2020-04-16 14-52-51

Fixes: #297

### CODE REVIEW

**Comment by joelvbernier** [comment]
Patrick -- here is a class I wrote to generalize the powder ring plotting.  The method `PowderLineOverlay.overlay(display_mode=<'raw' | 'cartesian' | 'polar')`

The though is that we will make an abstract base class to provide the common API for all of the different overlays (the others are `LaueSpotOverlay` (2-d like powder lines) and `RotationSeriesOverlay` (intrinsically 3-d, but can project to 2-d).

from the `examples/NIST_ruby/multiruby_dexelas/` instrument:

```
plo = PowderLineOverlay(plane_data, instr)
pg = plo.overlay(display_mode='raw')
fig, ax = plt.subplots()
ax.plot(pg['ff1'][:, 0], pg['ff1'][:, 1], 'c-')
```
Screenshot 2020-05-23 20 21 23
Note the the cartesian plot mode has a "fake" single-detector instrument defined in it, and that can be used to generate the cartesian overlay class; currently, the raw and cartesian modes are not actually handled differently in the `PowderLineOverlay` class.  Furthermore, the polar mode actually plots the same line overlay for each detector in the returned overlay; I thought about plotting on the detector extents in the polar mode as well, but that might look goofy (_i.e._, lines broken in eta).  Can either make it an option, or change the return type in that case to just be the (2θ, η).  Anyhow, a start.  

FWIW, I have included the Laue type overlay as well:
```
fig = plt.figure()
ax1 = fig.add_subplot(1,2,1, adjustable='box', aspect=1)
ax2 = fig.add_subplot(1,2,2, adjustable='box', aspect=1)

lo = LaueSpotOverlay(plane_data, instr, max_energy=150.)
pg = lo.overlay()

ax1.plot(pg['ff1'][:, 0], pg['ff1'][:, 1], 'c.')
ax2.plot(pg['ff2'][:, 0], pg['ff2'][:, 1], 'c.')
ax1.set_title('ff1')
ax2.set_title('ff2')
```
Screenshot 2020-05-23 21 43 37
Screen Shot 2020-05-23 at 9 49 28 PM

Code below.
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri May 22 18:06:07 2020

@author: joel
"""
import numpy as np

from hexrd import constants


nans_row = np.nan*np.ones((1, 2))


class PowderLineOverlay(object):
    def __init__(self, plane_data, instr, eta_steps=360):
        self._plane_data = plane_data
        self._instrument = instr
        self._eta_steps = eta_steps

    @property
    def plane_data(self):
        return self._plane_data

    @property
    def instrument(self):
        return self._instrument

    @property
    def eta_steps(self):
        return self._eta_steps

    @eta_steps.setter
    def eta_steps(self, x):
        assert isinstance(x, int), 'input must be an int'
        self._eta_steps = x

    @property
    def delta_eta(self):
        return 360./float(self.eta_steps)

    def overlay(self, display_mode='raw'):
        """
        """
        tths = self.plane_data.getTTh()

        etas = np.radians(
            self.delta_eta*np.linspace(
                0., self.eta_steps, num=self.eta_steps + 1
            )
        )
        point_groups = dict.fromkeys(self.instrument.detectors)
        for det_key, panel in self.instrument.detectors.iteritems():
            ring_pts = []
            for tth in tths:
                ang_crds = np.vstack([np.tile(tth, len(etas)), etas]).T
                if display_mode == 'polar':
                    ring_pts.append(np.vstack([ang_crds, nans_row]))
                elif display_mode in ['raw', 'cartesian']:
                    xys_full = panel.angles_to_cart(ang_crds)
                    xys, on_panel = panel.clip_to_panel(
                        xys_full, buffer_edges=False
                    )
                    diff_tol = np.radians(self.delta_eta) + 1e-4
                    ring_breaks = np.where(
                        np.abs(np.diff(etas[on_panel])) > diff_tol
                    )[0] + 1
                    n_segments = len(ring_breaks) + 1
                    if n_segments == 1:
                        ring_pts.append(np.vstack([xys, nans_row]))
                    else:
                        src_len = sum(on_panel)
                        dst_len = src_len + len(ring_breaks)
                        nxys = np.nan*np.ones((dst_len, 2))
                        ii = 0
                        for i in range(n_segments - 1):
                            jj = ring_breaks[i]
                            nxys[ii + i:jj + i, :] = xys[ii:jj, :]
                            ii = jj
                        i = n_segments - 1
                        nxys[ii + i:, :] = xys[ii:, :]
                        ring_pts.append(np.vstack([nxys, nans_row]))
            point_groups[det_key] = np.vstack(ring_pts)
        return point_groups


class LaueSpotOverlay(object):
    def __init__(self, plane_data, instr,
                 crystal_params=None, sample_rmat=None,
                 min_energy=5., max_energy=35.,
                 ):
        self._plane_data = plane_data
        self._instrument = instr
        if crystal_params is None:
            self._crystal_params = np.hstack(
                [constants.zeros_3,
                 constants.zeros_3,
                 constants.identity_6x1]
            )
        else:
            assert len(crystal_params) == 12, \
                "crystal parameters must have length 12"
        self._min_energy = min_energy
        self._max_energy = max_energy
        if sample_rmat is None:
            self._sample_rmat = constants.identity_3x3

    @property
    def plane_data(self):
        return self._plane_data

    @property
    def instrument(self):
        return self._instrument

    @property
    def crystal_params(self):
        return self._crystal_params

    @crystal_params.setter
    def crystal_params(self, x):
        assert len(x) == 12, 'input must be array-like with length 12'

    @property
    def min_energy(self):
        return self._min_energy

    @min_energy.setter
    def min_energy(self, x):
        assert x < self.max_energy
        self._min_energy = x

    @property
    def max_energy(self):
        return self._max_energy

    @max_energy.setter
    def max_energy(self, x):
        assert x > self.min_energy
        self._max_energy = x

    @property
    def sample_rmat(self):
        return self._sample_rmat

    @sample_rmat.setter
    def sample_rmat(self, x):
        assert isinstance(x, np.ndarray), 'input must be a (3, 3) array'

    def overlay(self, display_mode='raw'):
        sim_data = self.instrument.simulate_laue_pattern(
            self.plane_data,
            minEnergy=self.min_energy,
            maxEnergy=self.max_energy,
            rmat_s=self.sample_rmat,
            grain_params=[self.crystal_params, ])
        point_groups = dict.fromkeys(sim_data)
        for det_key, psim in sim_data.iteritems():
            xy_det, hkls_in, angles, dspacing, energy = psim
            idx = ~np.isnan(energy)
            if display_mode == 'polar':
                point_groups[det_key] = angles[idx, :]
            elif display_mode in ['raw', 'cartesian']:
                point_groups[det_key] = xy_det[idx, :]
        return point_groups
```

**Comment by joelvbernier** [comment]
Should I just merge this and we'll put in a new PR for adding the classes once we find a home for them in the repo?

**Comment by psavery** [comment]
Hi Joel! I think these classes look nice. I think we'll need to just convert them to python3 and then we can add them in.

**Comment by joelvbernier** [comment]
Will do today.  Should we merge this one anyhow then do a new PR?

**Comment by psavery** [comment]
I'm not sure about merging this one, @cryos or @cjh1 can decide.

We can convert it to python3 by the way, once we figure out a place to put it.

**Comment by joelvbernier** [comment]
I’ll make a PR with a proposed package.  Just need to run 2to3 and fix some import paths...  on it now.

**Comment by cjh1** [comment]
Lets resolve these conflicts and get this merged, we can make any improvement in a followup PR.

**Pull request merged**
