### PR TITLE
Re-work how extra wppf parameters are added

### PR DESCRIPTION
**Pull request by psavery**
This PR is primarily for re-working how the extra WPPF parameters are added. Instead of initializing a WPPF object and grabbing the extra parameters from it, the extra parameters are generated separately.

However, this PR also:

- Adds a toggle option for displaying the WPPF plot.
- Makes the Rietveld method functional (it now works - at least on a basic level).

example

Fixes: #741

### CODE REVIEW

**Comment by joelvbernier** [comment]
@saransh13 -- I'd like to see an option where the user can evaluate the current model, potentially even a mode where you can live update the parameters (like Maud) to futz with an initial guess.  Not sure if we should make that part of this PR or make a new one.

**Comment by joelvbernier** [comment]
@psavery and @saransh13 -- do we need to merge this to maintain the functionality of WPPF with the current hexrd master?  We can push the eval option I previously mentioned to another PR in that case, otherwise, let's add that feature to this one.

**Comment by psavery** [comment]
@joelvbernier Well, this fixes the issue of #741. But otherwise, it's not urgent to merge.

**Comment by joelvbernier** [comment]
gonna merge; the extra features I was alluding to require changes in hexrd, so we will handle that separately.

**Review by joelvbernier — APPROVED** [review]

**Pull request merged**
