### PR TITLE
fix to use mask from projection method

### PR DESCRIPTION
**Pull request by joelvbernier**
was causing an index error for detectors with invalid projections removed.

### CODE REVIEW

**Comment by joelvbernier** [comment]
I rebased this feature branch before adding my fix, which looks like it triggered a bunch o fmessages from pep8speaks; you want to fix those too?

**Comment by cjh1** [comment]
@joelvbernier The reason you are getting all the pep8 issues is it seems that you added bunch of duplicate files to ` build/lib/`? I am assuming this was by mistake?

**Comment by joelvbernier** [comment]
crap, yes -- that was not the intent.  Anyhow, must fix this because the TARDIS example won't run inpolar view without it.

**Comment by cjh1** [comment]
@joelvbernier Would you like me to try a clean it up?

**Comment by cjh1** [comment]
@joelvbernier I took the liberty of creating #444, I cherry picked what I think the two changes you made here on to a clean master. Let me know if that looks good to you.

**Pull request closed without merging**
