### PR TITLE
LLNL I/O Transform

### PR DESCRIPTION
**Pull request by bnmajor**
Addresses #492 tilt and translation needs, as well as incorporates the resources made available in HEXRD/hexrd#96

### CODE REVIEW

**Comment by bnmajor** [comment]
@joelvbernier -
The tilt is now updated in the config file, but the polar view does not look correct. The tilt values are currently handled by:
 - Reading in in the default values (ex: `[0.0, -2.22144147e+00, 2.22144147e+00]`)
 - Convert the angles from `None` to `Extrinsic ZXZ` (ex: `[9.208167479260441e-10, 1.5707963267948966, -3.1415926526689764]`)
 - Add in the rotation (ex: rotation of `0.031754860207618155` = `[9.208167479260441e-10, 1.5707963267948966, -3.109837792461358]`)
If you can see a step that I've skipped or done out of order, let me know.

Additionally, the template that you've provided for `IMAGE-PLATE-4` is coming in upside-down from the one that I had [previously](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/resources/templates/TARDIS/IMAGE-PLATE-4.txt). I'm wasn't sure if the one you have is the correct orientation, or if it should be the way it was before. From our discussion in #486 it seems like this may be flipped.

The new `IMAGE-PLATE-4` border:
ip4

**Comment by cjh1** [comment]
@joelvbernier Do you have any feedback on this or should be just go ahead and merge?

**Comment by joelvbernier** [comment]
@bnmajor, I found a typo in the ref TARDIS I put in resources.  There is a pending hexrd PR that fixes it, but I've attached it here if you want to test it out :-)
```
beam:
  energy: 10.2505
  vector:
    azimuth: 119.0
    polar_angle: 90.0
detectors:
  IMAGE-PLATE-2:
    pixels:
      columns: 901
      rows: 421
      size:
      - 0.1
      - 0.1
    buffer:
    - 0.2
    - 0.2
    transform:
      tilt:
      - -1.57079633e+00
      - 0.0
      - 0.0
      translation:
      - 0.0
      - -11.935
      - -25.08
  IMAGE-PLATE-4:
    pixels:
      columns: 901
      rows: 421
      size:
      - 0.1
      - 0.1
    buffer:
    - 0.2
    - 0.2
    transform:
      tilt:
      - 0.0
      - -2.22144147e+00
      - 2.22144147e+00
      translation:
      - 0.0
      - 11.935
      - -25.08
id: NXXXXXX-XXX
oscillation_stage:
  chi: 0.0
  translation:
  - 0.0
  - 0.0
  - 0.0
```

**Comment by bnmajor** [comment]
@joelvbernier Re-tested with the updated `TARDIS` boundary and config files, looks a lot better! :) 
updated_polar

**Review by cjh1 — APPROVED** [review]
LGTM

**Pull request merged**
