### PR TITLE
Add density editor to the material properties tab

### PR DESCRIPTION
**Pull request by psavery**
This modifies the density property on the unit cell. It currently
does not affect any other parts.

Screenshot from 2020-12-07 14-48-04

Fixes: #659 
Fixes: #670

Depends on: hexrd/hexrd#137

### CODE REVIEW

**Comment by psavery** [comment]
Screenshot from 2020-12-08 14-46-26

@joelvbernier @saransh13 Here is an updated view, where it is now read-only.

Let me know if I should round the number of decimal places to a certain number.

**Comment by joelvbernier** [comment]
This looks good to me.  LGTM!

**Review by joelvbernier — APPROVED** [review]

**Review by cjh1 — APPROVED** [review]

**Comment by psavery** [comment]
@joelvbernier @cjh1 I'll merge this as soon as HEXRD/hexrd#137 gets merged.

**Comment by saransh13** [comment]
@psavery Merged HEXRD/hexrd#137 to master. This is ready to merge too.

**Pull request merged**
