### PR TITLE
Masking bugs

### PR DESCRIPTION
**Pull request by bnmajor**
In testing the label changes in #618 I discovered two bugs, one of which broke the masking by hand in polar view. The updates to the `LineBuilder` class for the two-click line calibration broke the way masking by hand worked. For a quick a simple fix this adds the old `LineBuilder` class back in, but this can be fixed in the near future.

Below is a gif of all of the masking options in both polar and raw view being used successfully now, including when views are toggled.
masking

### CODE REVIEW

**Review by cjh1 — APPROVED** [review]
LGTM, @bnmajor Can you raise a issue to remove the duplicate code/refactor in the future.

**Comment by bnmajor** [comment]
Yes, added an issue in #622

**Comment by psavery** [comment]
FYI, the line builder is a tad bit different now, as of https://github.com/HEXRD/hexrdgui/pull/617

It was much simpler for me to work with in this way. But it doesn't do any more mpl_connect's or anything like that. The owning object forwards the button events to it.

**Comment by psavery** [comment]
Actually, I see that you mentioned that in the PR message now. Sorry, I didn't realize the line builder was used anywhere else.

**Pull request merged**
