### PR TITLE
Add UI to support config selection

### LINKED ISSUE #864: LLNL import config options
User needs to be able to:

1. Use the reference instrument (default)
2. Use loaded instrument
3. Load an instrument config

### PR DESCRIPTION
**Pull request by bnmajor**
Fixes #864

### CODE REVIEW

**Comment by bnmajor** [comment]
@joelvbernier I think this is ready to go, unless there are some common or specific use cases that we should test out first.

**Comment by joelvbernier** [comment]
Can you rebase this off of master?  We changed a function import path in hexrd in #893

**Comment by joelvbernier** [comment]
Load Instrument Config button is greyed out; can't select?

**Comment by bnmajor** [comment]
@joelvbernier There was bug that required you to toggle the `default` checkbox after selecting `Load Configuration` if it was previously toggled off in order to enable the load option. This is fixed now.

**Comment by joelvbernier** [comment]
testing right now!

**Comment by joelvbernier** [comment]
YASSSS -- works great!

**Review by joelvbernier — APPROVED** [review]

**Pull request merged**
