### PR TITLE
Run calibration and update hexrdgui with output

### PR DESCRIPTION
**Pull request by psavery**
This seems to work for the most part, except that the material
lattice parameters do not seem to be getting refined (it looks like
the lattice params output from the calibrator is always the same,
even though it is flagged as refinable).

Note that the user currently has to step through all overlays. They
cannot click the "Ok" button to exit early, or there will be errors
from the calibrator about list sizes not matching. This is hopefully
something we can fix in the future.

### CODE REVIEW

**Comment by joelvbernier** [comment]
understood -- shall I wait for a review or should we merge this up now for me to test?

**Comment by psavery** [comment]
We can merge and test if @cjh1 is good with it

**Review by cjh1 — APPROVED** [review]

**Comment by cjh1** [comment]
@joelvbernier Test away!

**Comment by psavery** [comment]
I might be getting this exception now:
```python
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/calibration_runner.py", line 139, in finish_line
    self.pick_next_line()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/calibration_runner.py", line 101, in pick_next_line
    self.finish()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/calibration_runner.py", line 214, in finish
    self.run_calibration()
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/calibration/calibration_runner.py", line 238, in run_calibration
    mat.latticeParameters = calibrator.params
  File "/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/utils.py", line 95, in make_new_pdata
    mat._newPdata()
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/material.py", line 194, in _newPdata
    hkls = self.unitcell.getHKLs(self._dmin.getVal('nm')).T
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/unitcell.py", line 1198, in getHKLs
    hkl = self.ChooseSymmetric(hkl_dsp, InversionSymmetry=True)
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/unitcell.py", line 1108, in ChooseSymmetric
    hkl = hkllist[mask,:].astype(np.int32)
IndexError: too many indices for array
```

I'll take a look a little later when I have a little more time...

**Comment by joelvbernier** [comment]
@saransh13 any idea on this?

**Comment by saransh13** [comment]
Looks like the an the hkls generated by the values of the lattice parameter and the dmin is an empty list. I'm not sure why that would be the case.

**Comment by joelvbernier** [comment]
time for some `pdb` @saransh13

**Pull request merged**
